localfood/localfood/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import  static # Add for sell.image
from django.conf import settings # Add for sell.image
from localfood.views import HomeView # Add HomeView
from localfood.views import UserCreateView, UserCreateDoneTV # Add for auth function  # 인증 기능을 위해 추가

urlpatterns = [
    path('admin/', admin.site.urls),
    # Add 3 urls for auth functions below / 인증 기능을 위해 아래 3개 url 정의, 추가
    path('accounts/', include('django.contrib.auth.urls')),  # Basic django's URLconf(/login/,logout/)
    path('accounts/register/',UserCreateView.as_view(),name='register'), # Define create account url
    path('accounts/register/done/',UserCreateDoneTV.as_view(),name='register_done'), # Define done url after creating account url
    #-----
    path('',HomeView.as_view(),name='home'), # Add Home view
    path('sell/', include('sell.urls')), # Add sell app's url
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT) # Add for sell.image

localfood/sell/urls.py
from django.contrib import admin
from django.urls import path
from sell import views

app_name = 'sell'

urlpatterns = [
    #Example: /sell/
    path('',views.SellLV.as_view(),name='index'),

    #Example: /sell/sell/99
    path('sell/<int:pk>/',views.SellDV.as_view(),name='sell_detail'),

    #Example: /sell/search/
    path('search/',views.SearchFormView.as_view(),name='global_search'),

    #Example: /sell/merchandise/add/
    path('merchandise/add/',views.MerchandiseCV.as_view(),name='merchandise_add'),

    #Example: /sell/merchandise/change
    path('merchandise/change/',views.MerchandiseChangeLV.as_view(),name='merchandise_change'),

    #Example: /sell/merchandise/update
    path('merchandise/<int:pk>/update/',views.MerchandiseUV.as_view(),name='merchandise_update'),

    #Example: /sell/merchandise/delete
    path('merchandise/<int:pk>/delete/',views.MerchandiseDelV.as_view(),name='merchandise_delete'),
]

localfood/sell/models.py
from django.db import models
from django.urls import reverse
from sell.fields import ThumbnailImageFieldFile
from sell.fields import ThumbnailImageField # Define custom field

# Create your models here.
class Merchandise(models.Model): # Define Merchandise table
    title=models.CharField('TITLE',max_length=30)
    brand=models.CharField('BRAND',max_length=30)
    slug = models.SlugField('SLUG',unique=True, allow_unicode=True, help_text='one word for title alias')
    price = models.FloatField('PRICE')
    image=ThumbnailImageField(upload_to='merchandise/%Y/%m')
    description = models.TextField('Merchandise Description',blank=True)
    rating = models.FloatField('RATING',blank=True,null=True)
    create_dt = models.DateTimeField('CREATE DATE',auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE',auto_now=True)
    owner = models.ForeignKey('auth.User',on_delete=models.CASCADE,verbose_name='OWNER',blank =True,null=True) # Add for add, editing function

    class Meta:
        ordering=('id',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('sell:sell_detail',args=(self.id,))

localfood/sell/forms.py
from django import forms

class SellSearchForm(forms.Form): #Define SearchForm by inheriting form class from django.forms
    search_word = forms.CharField(label='Search Word') # label => "Search Word" that is printed in front of form widget / it means <input type ="text"> in HTML.

localfood/localfood/views.py
from django.views.generic import TemplateView

#Add for 3 auth functions below.
from django.views.generic import CreateView # generic view -> for dealing with changing data in table
from django.contrib.auth.forms import  UserCreationForm
from django.urls import reverse_lazy # reverse() X-> urls.py module can't be loaded before doing and loading views.py module

#Add for add, edit function
from django.contrib.auth.mixins import AccessMixin # Distinguish proper permission or not , when processing handling view phase

class HomeView(TemplateView): #Define Home View
    template_name = 'home.html'


class UserCreateView(CreateView): # Define User Create View
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView): # Define User Create Done View
    template_name = 'registration/register_done.html'


# Add Mixin class for add, edit function
class OwnerOnlyMixin(AccessMixin): # Whether distinguish that the user has permission of this content or not
    raise_exception = True # 403 Exception
    permission_denied_message = "Owner only can update/delete the object" # 403 Exception message

    def dispatch(self,request, *args,**kwargs): # Overriding dispatch() method, to distinguish owner before get() method
        obj = self.get_object() # Get obejct from table
        if request.user != obj.owner:
            return self.handle_no_permission()
        return super().dispatch(request,*args,**kwargs)

localfood/sell/views.py
from django.shortcuts import render
from sell.models import Merchandise
from django.views.generic import ListView,DetailView
from django.views.generic import FormView  # Add for search function
from sell.forms import SellSearchForm  # Add for search function
from django.db.models import Q  # Add for search function
from django.shortcuts import render  # Add for search function

#Add these things for add,edit function below.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from localfood.views import OwnerOnlyMixin
from django.views.generic import CreateView,UpdateView,DeleteView

#Add for comment function
from django.conf import settings

# Create your views here.
class SellLV(ListView):
    model=Merchandise

# Edit class for comment function
class SellDV(DetailView):
    model=Merchandise

    # Add a method for comment function
    def get_context_data(self, **kwargs): # For adding context variable
        context = super().get_context_data(**kwargs) # Allocate context variables from original context variables coming from super() method
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}" # Get a value of context variables from settings.py
        context['disqus_id'] = f"merchandise-{self.object.id}-{self.object.slug}" # Get a value of context variables from settings.py = ex) merchandise-PK-SLUG
        context['disqus-url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}" # Define the name of page
        return context



#FormView -> if data is vaild , FormView class would do form_valid() function and redirect valid url.
class SearchFormView(FormView): # Define global searchForm
    form_class = SellSearchForm
    template_name = 'sell/global_search.html'

    def form_valid(self,form): # if data(that is from POST request) is valid ->True
        searchWord=form.cleaned_data['search_word'] # if data is valid, input data is in cleaned_data dictionary.
        sell_list=Merchandise.objects.filter(Q(title__icontains=searchWord)| Q(brand__icontains=searchWord)| Q(description__icontains=searchWord)).distinct() # icontains-> i ->Case sensitive X, distinct()->No duplicates

        context={} # Define context as dictionary form
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = sell_list

        return render(self.request,self.template_name,context) # No Redirection, return HttpResponse object

# Add class views for add, edit function below.
class MerchandiseCV(LoginRequiredMixin,CreateView): # Define Merchandise CreateView for every user in LOFOO
    model = Merchandise
    fields = ('title','brand','price','image','description')
    success_url = reverse_lazy('sell:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class MerchandiseChangeLV(LoginRequiredMixin,ListView):  # Define Merchandise ChangeView for every user in LOFOO
    model = Merchandise
    template_name = 'sell/merchandise_change_list.html'

    def get_queryset(self):
        return Merchandise.objects.filter(owner=self.request.user)

class MerchandiseUV(OwnerOnlyMixin,UpdateView): # Define Merchandise UpdateView for the merchandise's owner
    model = Merchandise
    fields = ('title','brand','price','image','description')
    success_url = reverse_lazy('sell:index')

class MerchandiseDelV(OwnerOnlyMixin,DeleteView): # Define Merchandise DeleteView for the merchandise's owner
    model= Merchandise
    success_url = reverse_lazy('sell:index')

localfood/sell/templates/sell/global_search.html
{% extends "base.html" %}

{% block title %}global_search.html{% endblock %}

{% block content %}

    <h1>Sell-Merchandise Search</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>

    <br/><br/>

    {% if object_list %}
        {% for merchandise in object_list %}
        <h2><a href='{{ merchandise.get_absolute_url }}'>{{ merchandise.title }}</a></h2>
        <img src="{{ merchandise.image.url }}" style="width: 40%;">
        <p><span >Brand: </span><span>{{ merchandise.brand }}</span></p>
        <p><span>Description: </span>{{ merchandise.description }}</p>
        {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}

localfood/sell/templates/sell/merchandise_change_list.html
{% extends "base.html" %}

{% block title %}LOFOO - Merchandise Change_list{% endblock %}

{% block content %}

    <h1>Sell- Merchandise Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="table-info">
            <th>Title</th>
            <th>Brand</th>
            <th>Price</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.brand }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'sell:merchandise_update' item.id %}">Update</a></td>
            <td><a href="{% url 'sell:merchandise_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

localfood/sell/templates/sell/merchandise_confirm_delete.html
{% extends "base.html" %}

{% block title %}LOFOO - Merchandise Delete {% endblock %}

{% block content %}

    <h1>Merchandise Delete</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

{% endblock %}

localfood/sell/templates/sell/merchandise_detail.html
{% extends "base.html" %}

{% block title %}Sell_Merchandise_detail{% endblock %}
<!--Add style for comment function to make this page looks well-->
{% block extra-style %}
<style>
.merchandise-body{
    width:80%;
    margin: auto;
    font-family:"Lucida Grande",Verdana,Arial,sans-serif;
    font-size:16px;
}
</style>
{% endblock extra-style %}

{% block content %}
    <div class = "merchandise-body">
        <div class="row"> 
            <div class="col-md-9">
                <a href="{{ object.image.url }}">
                    <img src="{{ object.image.url }}" style="width: 100%;">
                </a>
            </div>
    
            <ul class="col-md-3 mt-3">
                <br><br>
                <li class="h1">{{object.title}}</li>
                <br>
                <li class="h4">{{object.brand}}</li>
                <br>
                <li class="h4">Rating : {{object.rating}}</li>
                <hr>
                <li class="h4">Price : ${{object.price}}</li>
                <hr>
             <li class="h3">About this item</li>
                    {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                    {% else %}<p>(blank)</p>{% endif %}
            </ul>
        </div>

        <br>
        <div id="disqus_thread"></div>
    </div>
{% endblock %}

{% block extra-script %} <!-- Below is getting comments stored from DISQUS platform-->
    <script>
        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
        

        var disqus_config = function () {
        this.page.identifier = '{{disqus_id}}'; //Replace PAGE_IDENTIFIER with your page's unique identifier variable
        this.page.url = '{{disqus_url}}';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.title= '{{disqs_title}}'; // Name of page to show the title in Disqus site
        };
        
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://{{disqus_short}}.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock %}

localfood/sell/templates/sell/merchandise_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}LOFOO - New Merchandise Add{% endblock %}

{% block content %}
    <h1>Merchandise Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your photo.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    {% if form.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post" class="card pt-3">
    {% else %}
    <form action="." method="post" class="card pt-3">
    {% endif %}
    {% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.brand|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.brand|add_class:"form-control"|attr:"rows:1" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.price|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.price|add_class:"form-control"|attr:"rows:1" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>

{% endblock %}

localfood/sell/templates/sell/merchandise_list.html
{% extends "base.html" %}

{% block title %}Sell_All_Merchandise_List{% endblock %}

{% block content %}
    <h1>Sell List</h1>
    <br>

    <ul>
        {% for sell in object_list %}
        <li><a href="{% url 'sell:sell_detail' sell.id %}">{{ sell }}</a></li>
        {% endfor %}
    </ul>
    
{% endblock %}

localfood/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}LOFOO(Local Food){% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Local Food for Healthy World</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'sell:index' %}">All</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="">Seoul</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="">Incheon</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="">Daejon</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="">Junju</a></li>
             <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'sell:merchandise_add' %}">Sell_Merchandise</a>
                </div>
            </li>
            
            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Edit</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'sell:merchandise_change' %}">Change_Sell_Merchandise</a>
                </div>
            </li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="">Chat</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'sell:global_search' %}">Sell_Merchandise_Search</a>
                    <a class="dropdown-item" href="">User_Search</a> 
                </div>
            </li>
        </ul>

        <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
        </form>
        
        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            	    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                <div class="dropdown-menu">
            	    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            	    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            	    <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                <div class="dropdown-menu">
            	    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            	    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>

    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>


{% block footer %}{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

localfood/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}LOFOO(Local Food){% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/Main.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title {
    color: rgb(0, 204, 10);
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: rgb(0, 204, 10);
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">LOFOO(Local Food)</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>For Healthy Life</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Sell App</h3>
            <p>This application is sales bulletin board for local food.between customers and customers.
                The sales is B2C or C2C or B2B, everything is possible.
                But the important point is that the merchandises in that application is based on the user's location.
                You can sell your merchandises and buy merchandises by Sell application.
                It's also possible to update or delete your merchandises.</p>
        </div>
        <div class="col-sm-6">
            <h3>Chat App</h3>
            <p></p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim // + 2020 Yongju Seong</div>
</footer>
{% endblock %}